// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2EgLOxzOagcJ8HmeVLLFQ-Qp6Evku-4o',
    appId: '1:857839367146:web:fe3893bc8c85e4c689b893',
    messagingSenderId: '857839367146',
    projectId: 'melo-16e82',
    authDomain: 'melo-16e82.firebaseapp.com',
    storageBucket: 'melo-16e82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGeYS6a1Tx7mi3CBcuNnvzHb1b1SlSuEo',
    appId: '1:857839367146:android:c3e56e6d89de630989b893',
    messagingSenderId: '857839367146',
    projectId: 'melo-16e82',
    storageBucket: 'melo-16e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1Y14dz_JnAT1b10OGeE7TmIHAU0RRtM',
    appId: '1:857839367146:ios:78116efa3ee0700f89b893',
    messagingSenderId: '857839367146',
    projectId: 'melo-16e82',
    storageBucket: 'melo-16e82.firebasestorage.app',
    iosBundleId: 'com.example.melo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU1Y14dz_JnAT1b10OGeE7TmIHAU0RRtM',
    appId: '1:857839367146:ios:78116efa3ee0700f89b893',
    messagingSenderId: '857839367146',
    projectId: 'melo-16e82',
    storageBucket: 'melo-16e82.firebasestorage.app',
    iosBundleId: 'com.example.melo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2EgLOxzOagcJ8HmeVLLFQ-Qp6Evku-4o',
    appId: '1:857839367146:web:36ccc2125429045f89b893',
    messagingSenderId: '857839367146',
    projectId: 'melo-16e82',
    authDomain: 'melo-16e82.firebaseapp.com',
    storageBucket: 'melo-16e82.firebasestorage.app',
  );
}
